/* hello_world.c generated by valac 0.56.0, the Vala compiler
 * generated from hello_world.vala, do not modify */

#include "hello_world.h"
#include <glib.h>

static void
_vala_main (void)
{
	g_print ("Hello World!\n");
}

int
main (int argc,
      char ** argv)
{
	_vala_main ();
	return 0;
}

