/* hello_world.h generated by valac 0.56.0, the Vala compiler, do not modify */

#ifndef __HELLO_WORLD_H__
#define __HELLO_WORLD_H__

#include <glib.h>

G_BEGIN_DECLS

static void _vala_main (void);

G_END_DECLS

#endif
