/* hello_world_oop.h generated by valac 0.56.0, the Vala compiler, do not modify */

#ifndef __HELLO_WORLD_OOP_H__
#define __HELLO_WORLD_OOP_H__

#include <glib.h>

G_BEGIN_DECLS

#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

G_END_DECLS

#endif
